### PR TITLE
New contact section

### LINKED ISSUE #74: Design a Contact us section
**Description**

Design the contact section for PDA website

**Objective**

Contact section should contain 
- Map
- Email , phone number and address 
- Social medias 
- buttons

Files to be edited
- contact.ejs (in views folder)
- and public files (js/css/img  if Neccessary)

### PR DESCRIPTION
**Pull request by alphaX86**
**Description**

This PR fixes #74   

**Notes for Reviewer**
WIP don't merge ASAP. Tailwind CSS and Remixicons are added via CDN

### CODE REVIEW

**Comment by alphaX86** [comment]
Here's the screenshot of the work. Some work is still pending...

image

**Review by coding-geek21 — APPROVED** [review]
Merging it 🎉

**Comment by alphaX86** [comment]
Umm @coding-geek21 ... I said not to merge... 🙃 anyway a new PR will be opened for social links on those buttons

**Comment by coding-geek21** [comment]
> Umm @coding-geek21 ... I said not to merge... 🙃 anyway a new PR will be opened for social links on those buttons

Yeah fine make a new PR, Sorry i thought everything was finished 😅

**Pull request merged**
