### PR TITLE
Added Loader and animation on scroll

### PR DESCRIPTION
**Pull request by coding-geek21**
**Description**

This PR fixes #   

**Notes for Reviewer**

 Added loader and animation on scroll also
 on clicking logo in shows error (made it to redirect to home page)
**Module you've worked on**

- [ ] Frontend (Signup/Login)
- [ ] Backend (Login)
- [ ] Backend (Signup)
- [x] Homepage
- [ ] Others

**If you specified others, please mention...**

### CODE REVIEW

**Comment by alphaX86** [comment]
A favicon would be nice if present, could you add it @coding-geek21 ??

**Comment by coding-geek21** [comment]
> A favicon would be nice if present, could you add it @coding-geek21 ??

Sure I will add it, Can we add logo itself?

**Comment by alphaX86** [comment]
Yeah! Make sure it's 24x24 px and in favicon.ico format

**Comment by coding-geek21** [comment]
> Yeah! Make sure it's 24x24 px and in favicon.ico format

Added Favicon

**Review by alphaX86 — APPROVED** [review]

**Pull request merged**
